### ISSUE TITLE
gemma2-9b-it from GROQ not supported?

### ISSUE THREAD

**Issue by mxrkai** [yym68686/ChatGPT-Telegram-Bot#57] opened 2024-10-08 02:41 UTC
hi, i use GROQ and added model "gemma2-9b-it" but end up having this error

![image](https://github.com/user-attachments/assets/eba659ac-a06f-4b09-9b5b-545ce83a586d)

**Comment by yym68686** [comment] 2024-10-08 08:33
This is an error message from the provider, indicating that you do not have access to gemma2-9b-it. So this is not a bug with the bot, you should correctly set the API key permissions.

**Comment by mxrkai** [comment] 2024-10-08 09:06
hi, i have tried it on other platform but it works, the same api key from groq

![Screenshot_20241008-170449](https://github.com/user-attachments/assets/22cf0d20-1465-4b61-a22d-7741f9dfd2f3)

**Comment by yym68686** [comment] 2024-10-08 09:09
你可以发送一个临时的API key给我测试一下，仅需要很少的额度，包括API key API url，你的机器人部署命令，环境变量设置。发送到我的 yym68686@outlook.com 邮箱。以便于我复现你的问题。

**Comment by yym68686** [comment] 2024-10-21 13:28
Hello, as of now I have not received any emails, so this issue can be considered resolved. I will close this issue.

**Closed by yym68686** 2024-10-21 13:28 UTC
